language: python

# Tell travis-ci that we need the full git history. This is necessary
# for reno in the documentation build. If we do not clone the entire
# repository, travis does a shallow clone that only gives us the most
# recent commit.
git:
  depth: false

# https://docs.travis-ci.com/user/languages/python/

# required for Python >= 3.7
dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

# Test the nightly build of cpython, but ignore any failures.
# Add separate test environments for the docs and flake8 linter.
matrix:
  allow_failures:
    - python: "nightly"
  include:
    - env: BUILD=docs
    - env: BUILD=linter

# travis pre-installs some packages that may conflict with our test
# dependencies, so remove them before we set ourselves up. Also
# install pbr to avoid any setup_requires funkiness with
# pip/setuptools.
before_install:
  - pip uninstall -y nose mock
  - pip install pbr

install: pip install .[test] .[docs]

script:
  - ./tools/travis.sh
